version: '3.6'

services:
  wab-reverse-proxy:
    container_name: reverse-proxy
    build: reverse-proxy
    ports:
      - 8880:80
      - 8443:443
    environment:
      #HTTPS_UPSTREAM_SERVER_ADDRESS: 172.18.0.1
      HTTPS_UPSTREAM_SERVER_ADDRESS: wab-web
      HTTPS_UPSTREAM_SERVER_PORT: 8080
    volumes:
      - ./reverse-proxy/cert.pem:/cert.pem:ro
    links:
      - wab-web

  wab-web:
    container_name: wab-web
    image: openjdk:11-jre-slim
    volumes:
      - ../target:/var/target:rw
    entrypoint: [ "java", "-jar", "/var/target/localwab-web-1.0-SNAPSHOT.jar" ]
    ports:
        - "8091:8080"
    environment:
      IMPORT_CONTACTS_FROM: /wab-data/contacts.json
      ACCOUNT_VERIFICATION_CODE: 111222
      # https://developers.facebook.com/docs/whatsapp/api/health#api-keys
      WA_API_KEY: this-is-test-token
